version: '3.3'
services:
  nastushenka_performer:
    depends_on:
    - wordpress
    build:
      context: ../../.
      dockerfile: DockerfileDev
    ports:
    - '80:80'

  wordpress:
    depends_on:
    - db
    image: wordpress:latest
    ports:
    - "3000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: my_wordpress_db_password

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: my_wordpress_db_password
